const sites = [{
    name: "Statue of Liberty",
    continent: "America",
    country: "United States",
    region: "New York",
    image: "https://via.placeholder.com/400x250?text=Statue+of+Liberty",
    description: "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor, in the United States.",
},
{
    name: "Eiffel Tower",
    continent: "Europe",
    country: "France",
    region: "Ile-de-France",
    image: "https://via.placeholder.com/400x250?text=Eiffel+Tower",
    description: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France.",
},
{
    name: "Taj Mahal",
    continent: "Asia",
    country: "India",
    region: "Uttar Pradesh",
    image: "https://via.placeholder.com/400x250?text=Taj+Mahal",
    description: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the Yamuna river in the Indian city of Agra.",
},
{
    name: "Macchu Picchu",
    continent: "America",
    country: "Peru",
    region: "Cuzco",
    image: "https://via.placeholder.com/400x250?text=Macchu+Picchu",
    description: "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor, in the United States.",
},
{
    name: "Cristo Redentor",
    continent: "America",
    country: "Brazil",
    region: "Rio do Janeiro",
    image: "https://via.placeholder.com/400x250?text=Cristo+Redentor",
    description: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France.",
},
{
    name: "Chichen Itza",
    continent: "America",
    country: "Mexico",
    region: "Yucatan",
    image: "https://via.placeholder.com/400x250?text=Chichen+Itza",
    description: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the Yamuna river in the Indian city of Agra.",
},
];