const sites = [{
    name: "Statue of Liberty",
    continent: "america",
    country: "unitedStates",
    region: "New York",
    image: "https://via.placeholder.com/400x250?text=Statue+of+Liberty",
    description: "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor, in the United States.",
},
{
    name: "Eiffel Tower",
    continent: "europe",
    country: "france",
    region: "Ile-de-France",
    image: "https://via.placeholder.com/400x250?text=Eiffel+Tower",
    description: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France.",
},
{
    name: "Taj Mahal",
    continent: "asia",
    country: "india",
    region: "Uttar Pradesh",
    image: "https://via.placeholder.com/400x250?text=Taj+Mahal",
    description: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the Yamuna river in the Indian city of Agra.",
},
{
    name: "Macchu Picchu",
    continent: "america",
    country: "peru",
    region: "Cuzco",
    image: "https://via.placeholder.com/400x250?text=Macchu+Picchu",
    description: "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor, in the United States.",
},
{
    name: "Cristo Redentor",
    continent: "america",
    country: "brazil",
    region: "Rio do Janeiro",
    image: "https://via.placeholder.com/400x250?text=Cristo+Redentor",
    description: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France.",
},
{
    name: "Chichen Itza",
    continent: "america",
    country: "mexico",
    region: "Yucatan",
    image: "https://via.placeholder.com/400x250?text=Chichen+Itza",
    description: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the Yamuna river in the Indian city of Agra.",
},
];